### ISSUE TITLE
Do proper emacs packaging

### ISSUE THREAD

**Issue by milouse** [milouse/flycheck-grammalecte#1]
Faire un paquet propre à diffuser sur melpa et autre. J'ai aucune expérience dans ce domaine. La spécificité serait d'ajouter une fonction qui télécharge grammalecte au premier lancement du fichier .el. Je sais que le paquet [emacs-emojify](https://github.com/iqbalansari/emacs-emojify) fait quelque chose dans ce genre là

**Comment by milouse** [comment]
The automatic download is implemented in de693670974cef545aacf730724eaa2f5fad4e3e

**Comment by thomasluquet** [comment]
Du coup, il faut mettre à jours la doc pour effacer le git clone ?

**Comment by milouse** [comment]
J'ai mis un grand coup de balai dans le README, ça devrait être plus clair désormais.
