### ISSUE TITLE
Connection with server refused when using melpa-stable archive

### ISSUE THREAD

**Issue by PiOverFour** [milouse/flycheck-grammalecte#10]
Hi, I had the same issue as #7 , because the version available at melpa-stable is still the latest tagged version, v0.6 (see [here](https://github.com/melpa/melpa#melpa-stable)).
I could fix it by applying the URL change, but could you bump the version so that it’s updated in the archive?

(Maybe I should switch to MELPA, instead of -stable…)

Thank you!

**Comment by milouse** [comment]
I just pushed the new tag. I'll check tomorrow if Melpa stable has been updated successfully. Sorry for the delay.

**Comment by PiOverFour** [comment]
That was quick. Thank you very much! :)
