### ISSUE TITLE
synonyms buffer is empty

### ISSUE THREAD

**Issue by Bridouz** [milouse/flycheck-grammalecte#11]
Hi there, French emacs user here.

Just to report that when I want to fztch synonyms for a word the buffer with _synonymes_ and _antonymes_ is empty.

Emacs default config only with flycheck-grammalecte (latest version on MELPA).

Please tell me if you want some more debug nformations

**Comment by milouse** [comment]
Hello,

Did you try to search for your word directly on the web interface of the [CRISCO dictionary](https://crisco2.unicaen.fr/des/)? If there is no result for your word, the buffer will be empty (I agree I should add some default message saying no results have been found). In the contrary, if the DES has results for your word, I'd be happy if you share broken example here. Beware that the DES does not resolve plural or conjugation forms: only raw word or verb must be use (again, I agree I should add some warning somewhere.

Thanks for your interest and report!

**Comment by Bridouz** [comment]
I've just tried with the verb _parler_ and some other words (_peur_, _minuscule_).

No results, buffer is empty except for

```
* Synonymes

* Antonymes
```

Could it be because your `.el` does not use `crisco2` url (which redirects to it) ?

**Comment by milouse** [comment]
Oh, good catch, you are absolutely right. Thank you very much for your help (I was off lately, hence my long silence). It'll be fixed in the next releasex
