### ISSUE TITLE
problème installation / configuration ?

### ISSUE THREAD

**Issue by geoff21** [milouse/flycheck-grammalecte#12]
Bonjour,
déjà merci pour avoir développé cet outil.
(enfin repris et le garder en vie)
j'utilise doom emacs et je suis un newbie en « emacs-mode ».

bon, j'ai un problème et je ne sais pas trop d'où ça vient.
j'ai suivis les instructions pour l'installation. j'ai lancé «doom emacs» avec un fichier .org, introduit quelles que fautes, parfait tout fonctionne.
aujourd'hui je le relance et il ne me dit que des warning du genre “espace insécable“, “apostrophe typo”, ”espace en fin de ligne”.

rien sur les fautes d'orctographe, ou de conjugaison …………

il c'est passé quoi entre ces deux moments ?

je n'ai rien touché, modifié ou autre.

Cordialement.
et merci pour votre temps.
![test_grammalecte](https://user-images.githubusercontent.com/69142083/99964595-d4e2ae00-2d93-11eb-8776-d28df523f14a.png)

**Comment by milouse** [comment]
Bonjour,

Alors de mon côté, je ne connais pas du tout doom-emacs, il me semble qu’ils utilisent leur propre gestionnaire de paquet ou leur propre système de configuration non ?

Mais effectivement c’est étrange… Avez-vous procédé à des modifications dans les paramètres (`M-x customize` --> `Editing` --> `I18n` --> `Flycheck Grammalecte`) ? En effet la plupart des modifications ne sont prise en compte qu’après un redémarrage d’Emacs. En l’occurence il semble manquer chez vous les paramètres suivants : 

- `flycheck-grammalecte-report-spellcheck` qui est par défauf à `nil` (désactivé) car la correction orthographique de grammalecte est un peu foireuse et je pense qu’il est plus pertinent d’utiliser ispell pour l’orthographe. Vous pouvez consulter [ma config emacs à ce sujet](https://etienne.depar.is/emacs.d/utils.html#spellchecking) pour vous inspirer.
- `flycheck-grammalecte-report-grammar` qui est par défaut à `t` (activé). Il faudrait voir dans votre cas pourquoi il semble désormais désactivé. Après, votre capture d’écran ci-dessus ne comporte pas d’exemple frappant d’erreur de grammaire. Essayez d’ajouter une phrase du type « Ils mangeait des pomme. » pour voir si une erreur est détectée à « mangeait » et à « pomme ».

**Comment by geoff21** [comment]
merci pour votre réponse. la phrase « Ils mangeait des pomme. » ressort bien, je vais voir pour mieux configurer ispell.
merci pour le lien et les tips, ainsi que pour votre temps.

ps. oui doom utilise ses propres fichiers de config hors du répertoire .emacs.d/
télécharge des paquets pré config d'un repo et compile à chaque mise à jour.
mais il est tjrs possible d'installer des paquets elpa ou melpa. (je reste un newb en emacs-mode )

**Comment by bepolymathe** [comment]
> merci pour votre réponse. la phrase « Ils mangeait des pomme. » ressort bien, je vais voir pour mieux configurer ispell.
> merci pour le lien et les tips, ainsi que pour votre temps.
> 
> ps. oui doom utilise ses propres fichiers de config hors du répertoire .emacs.d/
> télécharge des paquets pré config d'un repo et compile à chaque mise à jour.
> mais il est tjrs possible d'installer des paquets elpa ou melpa. (je reste un newb en emacs-mode )

Est-ce que tu pourrais préciser ta config dans Doom Emacs ? Merci

**Comment by geoff21** [comment]
@bepolymathe 

dans le premier post tu peux voir un lien vers ses fichiers de config. très instructif

moi j'ai ça 
`(with-eval-after-load 'ispell
  ;; For windows
  ;;; Aspell au lieu de ispell
  ;(add-to-list 'exec-path "D:/Applis/Aspell/bin/")
  ;(setq ispell-program-name "aspell")
  ;; For ispell
  ;(setq ispell-personal-dictionary "~/.aspell.fr.pws")
  ;;; Hunspell au lieu de ispell
  (setq ispell-program-name "hunspell"
        ispell-dictionary "fr_FR"
        ispell-current-dictionary "fr_FR"))

;;(with-eval-after-load 'flycheck
;;  (flycheck-grammalecte-setup))
`dans config.el

et 
`;;(package! flycheck-grammalecte)`
dans package.el

en comment pour le moment, le serveur était off et bloquait la mise à jour de DoomEmacs.
