### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bepolymathe** [milouse/flycheck-grammalecte#13]
Bonjour, 

Merci pour ce travail. Après un changement de machine, je tente Doom Emacs (qui est pas mal du tout) mais je voudrais intégrer mon correcteur grammatical préféré. 

J’ai le message d’erreur suivant : 
![image](https://user-images.githubusercontent.com/29939805/108193149-6eacc380-7115-11eb-9b24-aaa589db6287.png)

Et ma version actuelle est celle-ci :thinking: 
![image](https://user-images.githubusercontent.com/29939805/108193234-8421ed80-7115-11eb-977e-93df969252e5.png)

J’ai installé "flycheck-grammalecte" depuis MELPA et j’ai 

`(flycheck-grammalecte-setup)
`
dans mon fichier de config. 

![image](https://user-images.githubusercontent.com/29939805/108195434-0ad7ca00-7118-11eb-8921-cea8be0a352f.png)

Qu’ai-je raté ?
Merci ;-) (c’est cool d’écrire un peu en français sur Github !)

**Comment by mdphoto** [comment]
Salut,

J'utilise DoomEmacs également.
Le problème vient probablement du faîte que tu as installé le package avec MELPA Doom utilise un fonctionnement différent pour l'installation des packages.
Ajoute (package! flycheck-grammalecte) dans ton fichier de configuration .doom/packages.el

**Comment by bepolymathe** [comment]
Merci de ton retour @mdphoto 

> Ajoute (package! flycheck-grammalecte) dans ton fichier de configuration .doom/packages.el

Oui c’est justement ce que j’ai fait... C’est comme cela que je l’ai installé. :thinking: 
Quelle est ta version de flycheck ?

**Comment by bepolymathe** [comment]
> Je me demande si ça changerait quelque chose de l’installer depuis github

Du coup j’ai essayé. Ça change rien. Je suspecte plus un problème avec python mais c’est pas ma partie...

**Comment by mdphoto** [comment]
Effectivement, c'est un problème Python.
Tu as installé grammalecte sur ton OS ?
Pour reproduire le problème tu peux dans un terminal faire 
python
>>>import gramalecte
Ctr D pour quitter

**Comment by bepolymathe** [comment]
Oh la honte... c’était juste ça. Il me manquait le paquet "python3-grammalecte-noarch" (mal installé). 
Merci @mdphoto !

**Comment by milouse** [comment]
Il existe une fonction dans ce package pour installer grammalecte en locale (sans nécessité d’installer grammalecte au niveau de l’OS). Une fois flycheck-grammalecte installé et activé dans vos configs, il vous suffit d’appeler `flycheck-grammalecte-download-grammalecte`

**Comment by bepolymathe** [comment]
Oui c’est ce que j’avais essayé de faire... maintenant il semble en fait que j’ai un conflit puisque j’ai une proposition de mise à jour de grammelecte lorsque je redémarre Emacs.

**Comment by bepolymathe** [comment]
![image](https://user-images.githubusercontent.com/29939805/108258601-7fcef200-7160-11eb-9768-bf04b0ee429a.png)
