### ISSUE TITLE
Pas de correction entre deux blocs de code en org-mode

### ISSUE THREAD

**Issue by ImAReplicant** [milouse/flycheck-grammalecte#15]
Bonjour,
Lorsque du texte se situe entre deux blocs de code (#+begin_src #+end_src) en org-mode la correction ne fonctionne pas :

![Capture d’écran du 2022-01-20 11-13-26](https://user-images.githubusercontent.com/71564949/150322363-d22aa08f-82a4-4700-a338-6f17fdc319fc.png)

Je crois que le problème vient des expressions régulières du fichier flycheck-grammalecte.el. 
Modifier la ligne 
`(org-mode "(?ims)^[ \t]*#\\+begin_src.+#\\+end_src"`
par
`(org-mode "(?ims)^[ \t]*#\\+begin_src.*?#\\+end_src"`
semble corriger le problème.

**Comment by milouse** [comment]
(je réponds ici pour les deux tickets)

Merci beaucoup pour vos rapports ! Je vais essayer de corriger ces problèmes au plus vite. Je pense que vous avez tapé dans le mille pour le souci de la regexp.

**Comment by rbocheux** [comment]
Bonjour,

Cette correction permet bien d’avoir la détection des erreurs entre deux blocs de code, par contre ça m’a rajouté des détections à l’intérieur des blocs de code.
![flycheck-grammalecte](https://user-images.githubusercontent.com/45258531/167144013-3510bf84-f15f-44c8-9496-fbc0308628f3.png)
Je n’ai fait que la modification mentionnée par ImAReplicant, sinon je n’ai aucune détection dans mon fichier org (hormis la table des matières qui me crée des fausses alarmes à causes des tirets, mais ça, c'est un autre problème).

Je ne connais pas bien les expressions régulières dans emacs, mais visiblement la zone entre `#+begin_src` et `#+end_src` n’est pas bien délimitée.
Si vous avez une solution, je suis preneur. Ça serait super de pouvoir utiliser grammalecte sur les fichiers org, sans avoir trop de fausses détections.
