### ISSUE TITLE
Ajouter une option pour ne pas afficher les erreurs typographiques

### ISSUE THREAD

**Issue by rbocheux** [milouse/flycheck-grammalecte#19]
Bonjour,

Je vois sur le site de grammalecte qu’il est possible de désactiver les erreurs typographiques. Ce serait une bonne idée d’ajouter cette option (comme il y a déjà ce choix pour les espaces ou les apostrophes), notamment parce que cela crée des faux positifs dans mes fichiers org, quand il y a une table des matières.
Chaque tiret de la table des matières est indiquée comme une erreur. C’est la même chose pour les toutes les listes des fichiers org en fait.

En tout cas merci pour le package emacs, c’est super de pouvoir utiliser grammalecte !

**Comment by ImAReplicant** [comment]
Bonjour, 

Si tu veux tu peux ignorer certaine correction grâce à `flycheck-grammalecte-filters`.
Voici ce que j’ai fait dans ma config pour ignorer les tirets et guillemets :

```
(setq flycheck-grammalecte-filters '("(?im)[ \t]*-.+$" ; Désactive - (Dans le sommaire par exemple)
				     "(?im)\""))       ; Désactive " " -> « »
```

**Comment by rbocheux** [comment]
Ah oui super, j'avais oublié qu'on pouvait ajouter des filtres perso.
Merci, c'est largement suffisant !
