### ISSUE TITLE
Connection refused avec www.dicollecte.org

### ISSUE THREAD

**Issue by Bridouz** [milouse/flycheck-grammalecte#7]
Hi,

I've just installed your package and `flycheck-grammalecte-download-grammalecte` returns erros about connection refused. In fact [www.dicollecte.org](www.dicollecte.org) is offline at the moment.
Is it possible to download `Grammalecte` from [https://grammalecte.net/grammalecte/zip/Grammalecte-fr-v0.6.5.zip](https://grammalecte.net/grammalecte/zip/Grammalecte-fr-v0.6.5.zip) instead ?

Thanks

**Comment by milouse** [comment]
Fixed by #8

**Comment by milouse** [comment]
And thank you very much for your contribution :)
