### ISSUE TITLE
Make it possible to avoid questions

### ISSUE THREAD

**Issue by Schnouki** [milouse/flycheck-grammalecte#9]
Hi,

During startup, if Emacs restores a buffer in a mode supported by flycheck-grammalecte, it will run `flycheck-grammalecte--download-grammalecte-if-needed`, which will then ask the "Download it now?" question with `yes-or-no-p`. This is fine... Except that it blocks when starting Emacs in daemon mode. Which is extra-annoying when you can't see the startup output, for instance when it's auto-started by systemd on user login...

Would it be possible to add a `defcustom` that doesn't ask the question and always downloads the Grammalecte data if needed? (Or doesn't download it, like a choice between `t`, `nil` and `'ask`...)

Thanks!

**Comment by milouse** [comment]
Yes, it's possible.

I'll try to work on it ASAP.

Thank you for your interest and your report :)

**Comment by milouse** [comment]
Sorry @Schnouki I just realize I didn't tell you I've pushed a fix for your issue. Can you try if the current master fix your needs ?

You dl package from melpa (NOT melpa-stable) and add a new variable to your .init file:

`(setq flycheck-grammalecte-download-without-asking t)`

Thank you very much.

**Comment by Schnouki** [comment]
Thanks a lot @milouse! Updated my packages, added the variable to my config file, removed the grammalecte folder and restarted Emacs: it works as expected and downloads grammalecte without asking :slightly_smiling_face: 

Thanks for fixing this and letting me know!
